import { StyleSheet } from "react-native";
import { FontFamilyId, resolveAppFont, resolveBodyFont, resolveHeadingFont } from "../fontFamily";
import {
  BODY_LINE_HEIGHT,
  RUBRIC_LINE_HEIGHT,
  liturgyLineHeight,
} from "../liturgyTypography";

export const makeStyles = (colors: any, fontSize: number, fontFamilyId: FontFamilyId, isBold?: boolean, lineSpacing = 1) => {
  const bodyFont = resolveBodyFont(fontFamilyId, !!isBold);
  const headingFont = resolveHeadingFont(fontFamilyId);
  const subtitleFont = resolveAppFont(fontFamilyId, "bold");
  const lh = (pt: number, ratio: number) => liturgyLineHeight(pt, ratio, lineSpacing);
  const bodyLh = () => lh(fontSize, BODY_LINE_HEIGHT);
  const titlePt = (scale: number) => Math.round(fontSize * scale);

  return StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  loadErrorBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
    gap: 16,
  },
  loadErrorTitle: {
    fontSize: Math.round(fontSize * 0.85),
    fontWeight: "800",
    color: colors.textPrimary,
    textAlign: "center",
  },
  loadErrorText: {
    fontSize: Math.round(fontSize * 0.6),
    color: colors.textSecondary,
    textAlign: "center",
    lineHeight: Math.round(fontSize * 0.95),
  },
  loadErrorBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 12,
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 14,
    backgroundColor: colors.primary,
    minHeight: 64,
  },
  loadErrorBtnText: {
    fontSize: Math.round(fontSize * 0.75),
    fontWeight: "700",
    color: colors.onPrimary,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    minHeight: 44,
    minWidth: 88,
  },
  backBtnText: { fontSize: Math.round(fontSize * 0.6), color: colors.textPrimary, fontWeight: "600" },
  title: { fontSize: Math.round(fontSize * 0.9), fontWeight: "700", color: colors.textPrimary },
  fontBtns: {
    flexDirection: "row",
    gap: 6,
    marginRight: 8,
    marginLeft: 6,
    alignItems: "center",
  },
  // Blocco saluto iniziale: dopo "A. E con il tuo spirito" lasciamo una
  // riga vuota di separazione tra le formule alternative.
  salutoBlock: {
    marginBottom: Math.round(fontSize * 1.0),
  },
  content: { padding: 16, paddingTop: 8, paddingBottom: 32 },
  dayBannerWrap: { marginBottom: 16 },
  togglesBox: {
    padding: 20,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
    marginBottom: 24,
    gap: 14,
  },
  partsPanel: {
    padding: 14,
    paddingBottom: 10,
    borderWidth: 2,
    borderColor: colors.liturgicalGreen,
    borderRadius: 14,
    backgroundColor: colors.surface,
    marginBottom: 24,
    gap: 14,
  },
  partsPanelTitle: {
    fontSize: Math.round(fontSize * 0.58),
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.7,
    color: colors.liturgicalGreen,
    marginBottom: 2,
  },
  toggleLabelCol: {
    flex: 1,
    paddingRight: 8,
  },
  toggleSubLabel: {
    fontSize: Math.round(fontSize * 0.55),
    color: colors.textSecondary,
    fontWeight: "600",
    marginTop: 2,
  },
  choicesSummary: {
    padding: 16,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
    marginTop: 20,
    marginBottom: 16,
    gap: 8,
  },
  choicesSummaryRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingVertical: 4,
  },
  choicesSummaryLabel: {
    flex: 0.42,
    fontSize: Math.round(fontSize * 0.62),
    color: colors.textSecondary,
    fontWeight: "600",
  },
  choicesSummaryValue: {
    flex: 0.58,
    fontSize: Math.round(fontSize * 0.68),
    color: colors.textPrimary,
    fontWeight: "700",
  },
  toggleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  toggleLabel: { fontSize: Math.round(fontSize * 0.75), color: colors.textPrimary, fontWeight: "600" },
  partBox: {
    marginBottom: 2,
    paddingBottom: 0,
    borderBottomWidth: 0,
  },
  // === Tutti i titoli condividono la stessa "regola di spazio" ===
  // marginBottom: 6 fissa la distanza titolo→testo.
  // lineHeight = fontSize del titolo (no extra leading) per un gap visivo uniforme.
  // marginTop: 0 (lo spazio sopra è gestito dal partBox).
  sectionTitle: {
    fontSize: Math.round(fontSize * 1.05),
    fontFamily: headingFont.fontFamily,
    fontWeight: headingFont.fontWeight,
    color: colors.accentSection,
    marginTop: 0,
    marginBottom: 6,
    lineHeight: Math.round(fontSize * 1.05),
  },
  // Titolo per sezioni rituali macro (Riti Introduzione, Liturgia Parola, ecc.)
  ritoTitle: {
    fontSize: Math.round(fontSize * 0.95),
    fontFamily: headingFont.fontFamily,
    fontWeight: headingFont.fontWeight,
    color: colors.accentRito,
    marginTop: 0,
    marginBottom: 6,
    lineHeight: Math.round(fontSize * 0.95),
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  // Titolo per antifone d'ingresso/comunione, sequenza, acclamazione al Vangelo
  antifonaTitle: {
    fontSize: Math.round(fontSize * 0.85),
    fontFamily: headingFont.fontFamily,
    fontWeight: headingFont.fontWeight,
    color: colors.accentAntifona,
    marginTop: 0,
    marginBottom: 6,
    lineHeight: Math.round(fontSize * 0.85),
  },
  // Titolo per le letture (Prima, Salmo, Seconda, Vangelo)
  readingTitle: {
    fontSize: Math.round(fontSize * 0.85),
    fontFamily: headingFont.fontFamily,
    fontWeight: headingFont.fontWeight,
    color: colors.accentReading,
    marginTop: 0,
    marginBottom: 6,
    lineHeight: Math.round(fontSize * 0.85),
  },
  // Titolo per orazioni proprie (Colletta, Sulle offerte, Dopo la comunione)
  orazioneTitle: {
    fontSize: Math.round(fontSize * 0.85),
    fontFamily: headingFont.fontFamily,
    fontWeight: headingFont.fontWeight,
    color: colors.accentOrazione,
    marginTop: 0,
    marginBottom: 6,
    lineHeight: Math.round(fontSize * 0.85),
  },
  subtitle: {
    fontSize: Math.round(fontSize * 0.85),
    fontFamily: subtitleFont.fontFamily,
    fontWeight: subtitleFont.fontWeight,
    color: colors.textPrimary,
    marginTop: 0,
    marginBottom: 6,
    lineHeight: Math.round(fontSize * 0.85),
  },
  // Titolo dei tropari della Formula C dell'Atto Penitenziale.
  // Arancio brillante per distinguere visivamente le serie di invocazioni
  // (es. "1. Via, Verità, Vita", "Formula introduttiva") dalle invocazioni
  // C./A. che le seguono. Coerente con la palette esistente.
  troparioTitle: {
    fontSize: Math.round(fontSize * 0.85),
    fontFamily: headingFont.fontFamily,
    fontWeight: headingFont.fontWeight,
    color: colors.accentTropario,
    marginTop: 8,
    marginBottom: 6,
    lineHeight: Math.round(fontSize * 1.0),
  },
  peTitle: {
    fontSize: Math.round(fontSize * 0.78),
    fontFamily: headingFont.fontFamily,
    fontWeight: headingFont.fontWeight,
    color: colors.accentPe,
    marginTop: 0,
    marginBottom: 8,
    lineHeight: Math.round(fontSize * 0.95),
  },
  prefaceTitle: {
    fontSize: Math.round(fontSize * 0.78),
    fontFamily: headingFont.fontFamily,
    fontWeight: headingFont.fontWeight,
    color: colors.accentPe,
    marginTop: 0,
    marginBottom: 8,
    lineHeight: Math.round(fontSize * 0.95),
  },
  peConsecration: {
    color: colors.accentPeConsecration,
    fontFamily: bodyFont.fontFamily,
    fontWeight: bodyFont.fontWeight,
  },
  peRubric: {
    fontSize: Math.round(fontSize * 0.85),
    fontStyle: "italic",
    color: colors.rubrics,
    fontFamily: bodyFont.fontFamily,
    fontWeight: bodyFont.fontWeight,
    lineHeight: Math.round(fontSize * 1.35),
    letterSpacing: 0.8,
  },
  // Dossologia conclusiva ("PER CRISTO, CON CRISTO E IN CRISTO..."): stile
  // uniforme per tutte le PE — bianco, maiuscolo, peso REGULAR (alleggerito
  // su richiesta utente: il bold rendeva il testo troppo pesante a video).
  peDossologia: {
    fontSize: fontSize,
    lineHeight: bodyLh(),
    color: colors.textPrimary,
    fontFamily: bodyFont.fontFamily,
    fontWeight: bodyFont.fontWeight,
    marginTop: 4,
    marginBottom: 8,
  },
  // Stile per "Umili e pentiti" - testo della preghiera in rosso (rubrica)
  umili: {
    fontSize: Math.round(fontSize * 0.85),
    fontStyle: "italic",
    color: colors.rubrics,
    fontFamily: bodyFont.fontFamily,
    fontWeight: bodyFont.fontWeight,
    marginVertical: 6,
    lineHeight: lh(Math.round(fontSize * 0.85), RUBRIC_LINE_HEIGHT),
  },
  text: {
    fontSize: fontSize,
    lineHeight: bodyLh(),
    color: colors.textPrimary,
    fontFamily: bodyFont.fontFamily,
    fontWeight: bodyFont.fontWeight,
    marginTop: 0,
    marginBottom: 8,
  },
  rubric: {
    fontSize: Math.round(fontSize * 0.7),
    fontStyle: "italic",
    color: colors.rubrics,
    marginVertical: 4,
    lineHeight: lh(Math.round(fontSize * 0.7), RUBRIC_LINE_HEIGHT),
    fontFamily: bodyFont.fontFamily,
    fontWeight: bodyFont.fontWeight,
  },
  // Inline "R." rosso per il ritornello del Salmo Responsoriale
  salmoRit: {
    color: colors.rubrics,
    fontFamily: headingFont.fontFamily,
    fontWeight: headingFont.fontWeight,
  },
  // Stile per il salmo responsoriale: usa un singolo <Text> multilinea
  // così le strofe non hanno doppio spazio fra una riga e l'altra.
  salmoText: {
    fontSize: fontSize,
    lineHeight: bodyLh(),
    color: colors.textPrimary,
    fontFamily: bodyFont.fontFamily,
    fontWeight: bodyFont.fontWeight,
    marginVertical: 4,
  },
  celebrante: {
    fontSize: fontSize,
    color: colors.textPrimary,
    fontFamily: bodyFont.fontFamily,
    fontWeight: bodyFont.fontWeight,
    marginVertical: 6,
    lineHeight: bodyLh(),
  },
  // Risposte dell'assemblea (A. ...): corsivo, -1pt rispetto al base, NON bold.
  // Pensato per dare meno "peso" visivo alle risposte rispetto alle parti del
  // celebrante (che restano fontSize regular), mantenendo comunque la
  // distinzione tipografica (italico).
  assemblea: {
    fontSize: Math.max(12, fontSize - 1),
    fontStyle: "italic",
    color: colors.textPrimary,
    fontFamily: bodyFont.fontFamily,
    fontWeight: bodyFont.fontWeight,
    marginVertical: 6,
    lineHeight: lh(Math.max(12, fontSize - 1), BODY_LINE_HEIGHT),
  },
  block: { marginVertical: 10 },
  // Pulsante grande sulla pagina del Congedo: passa alla modalità "Celebra la
  // Messa" (lettura pulita per l'altare). Pensato per essere ben visibile e
  // facile da centrare con il dito anche per chi ha la vista debole.
  completeRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 10,
    marginTop: 28,
    marginBottom: 12,
  },
  celebrateNowBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderRadius: 14,
    backgroundColor: colors.liturgicalGreen,
    minHeight: 72,
  },
  celebrateNowBtnMain: {
    flex: 1,
    marginTop: 0,
    marginBottom: 0,
  },
  favoriteBtn: {
    width: 72,
    minHeight: 72,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  favoriteBtnActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  favoriteHint: {
    marginTop: 8,
    fontSize: Math.round(fontSize * 0.58),
    fontWeight: "700",
    color: colors.primary,
    textAlign: "center",
  },
  celebrateNowBtnText: {
    fontSize: Math.round(fontSize * 0.7),
    fontWeight: "800",
    color: colors.onPrimary,
    textAlign: "center",
    flexShrink: 1,
  },
  // Bottoni per scegliere fra 26 benedizioni solenni: layout flex-wrap
  solemnChoiceBtn: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 10,
    minHeight: 56,
    flexBasis: "48%",
    flexGrow: 1,
  },
  solemnChoiceText: {
    color: colors.textPrimary,
    fontSize: Math.round(fontSize * 0.55),
    fontWeight: "700",
  },
  // Bottoni numerati (per orazioni sul popolo 1-28): griglia compatta
  numChoiceBtn: {
    minWidth: 56,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 56,
  },
  numChoiceText: {
    color: colors.textPrimary,
    fontSize: Math.round(fontSize * 0.7),
    fontWeight: "800",
  },
  orazionePopoloPreview: {
    marginTop: 14,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 10,
    padding: 16,
    backgroundColor: colors.surface,
  },
  // Suggerimento sulla prossima pagina
  solemnHint: {
    marginTop: 14,
    color: colors.primary,
    fontSize: Math.round(fontSize * 0.55),
    fontStyle: "italic",
    fontWeight: "600",
  },
  // Box per ogni formula dell'atto penitenziale C (separazione visiva)
  penitentialFormulaBox: {
    marginTop: 18,
    paddingTop: 14,
    paddingBottom: 6,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  dialogBlock: { marginVertical: 6 },
  readingBlock: { marginVertical: 6 },
  pageStatusBar: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: colors.surface,
    borderBottomWidth: 2,
    borderBottomColor: colors.border,
  },
  pageStatusText: {
    fontSize: Math.round(fontSize * 0.7),
    fontWeight: "700",
    color: colors.textPrimary,
    textAlign: "center",
  },
  navBar: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.surface,
    borderTopWidth: 2,
    borderTopColor: colors.border,
  },
  navBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    minHeight: 72,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  navBtnPrimary: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  navBtnDisabled: {
    opacity: 0.4,
  },
  navBtnText: {
    fontSize: Math.round(fontSize * 0.8),
    fontWeight: "700",
    color: colors.textPrimary,
  },
  tapZone: {
    position: "absolute",
    top: 0,
    bottom: 0,
    backgroundColor: "transparent",
  },
  tapHint: {
    position: "absolute",
    bottom: 16,
    left: 16,
    right: 16,
    alignItems: "center",
  },
  tapHintText: {
    fontSize: Math.round(fontSize * 0.45),
    color: colors.textSecondary,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
    overflow: "hidden",
    fontStyle: "italic",
    fontWeight: "600",
    textAlign: "center",
  },
  startCelebrationBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    backgroundColor: colors.primary,
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 14,
    marginTop: 24,
    minHeight: 88,
  },
  startCelebrationBtnText: {
    fontSize: Math.round(fontSize * 0.8),
    fontWeight: "700",
    color: colors.onPrimary,
  },
  choiceRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginVertical: 14 },
  choiceBtn: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    minHeight: 64,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.surface,
    justifyContent: "center",
  },
  choiceBtnActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  choiceBtnText: { fontSize: Math.round(fontSize * 0.7), color: colors.textPrimary, fontWeight: "700" },
  selectorBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: 10,
    marginVertical: 8,
    minHeight: 56,
  },
  selectorBtnText: { fontSize: Math.round(fontSize * 0.9), color: colors.primary, fontWeight: "700" },
  // Variante compatta inline (es. accanto al titolo "Preghiera Eucaristica")
  selectorBtnInline: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: 8,
    marginLeft: 16,
    minHeight: 50,
  },
  selectorBtnInlineText: { fontSize: Math.round(fontSize * 0.8), color: colors.primary, fontWeight: "700" },
  // Riga flex per affiancare titolo + bottone "Scegli ..."
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 10,
    gap: 6,
  },
  // === Selettori Tempo Liturgico / Rito Particolare (PE) ===
  peSelectorsRow: {
    flexDirection: "row",
    gap: 14,
    marginTop: 6,
    marginBottom: 14,
    flexWrap: "wrap",
  },
  peSelectorBtn: {
    flex: 1,
    minWidth: 200,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: "transparent",
    borderWidth: 1.5,
    borderColor: colors.accentPeSelectorBorder,
    minHeight: 70,
  },
  peSelectorLabel: {
    fontSize: Math.round(fontSize * 0.65),
    color: colors.accentPeSelectorLabel,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 6,
  },
  peSelectorValueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
  },
  peSelectorValue: {
    color: colors.accentPeSelectorValue,
    fontSize: Math.round(fontSize * 0.85),
    fontWeight: "600",
    flex: 1,
  },
  // Modale picker per i selettori PE
  peModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.75)",
    justifyContent: "center",
    padding: 24,
  },
  peModalCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 24,
    borderWidth: 3,
    borderColor: colors.accentPeModalBorder,
  },
  peModalTitle: {
    color: colors.textPrimary,
    fontSize: Math.round(fontSize * 0.85),
    fontWeight: "800",
    marginBottom: 18,
  },
  peModalOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 18,
    paddingHorizontal: 14,
    borderRadius: 10,
    minHeight: 64,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  peModalOptionActive: { backgroundColor: colors.accentPeModalActiveBg },
  peModalOptionText: { color: colors.textPrimary, fontSize: Math.round(fontSize * 0.75), flex: 1, fontWeight: "600" },
  peModalClose: {
    alignItems: "center",
    paddingVertical: 16,
    marginTop: 10,
    backgroundColor: colors.accentPeModalBorder,
    borderRadius: 10,
    minHeight: 60,
    justifyContent: "center",
  },
  peModalCloseText: { color: colors.onPrimary, fontWeight: "800", fontSize: Math.round(fontSize * 0.75) },
  listItem: {
    padding: 22,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.surface,
    marginBottom: 12,
    minHeight: 90,
  },
  listItemActive: { borderColor: colors.primary, borderWidth: 4 },
  listItemText: { fontSize: Math.round(fontSize * 0.8), color: colors.textPrimary, fontWeight: "700" },
  listItemSub: { fontSize: Math.round(fontSize * 0.6), color: colors.textSecondary, marginTop: 6 },
  badgeSeasonal: { fontSize: Math.round(fontSize * 0.5), color: colors.primary, fontWeight: "800", marginBottom: 6, letterSpacing: 1 },
  solemnToggle: { borderWidth: 2, borderColor: colors.border, borderRadius: 10, padding: 16, backgroundColor: colors.surface },
  acclamationBox: {
    marginVertical: 18,
    padding: 18,
    borderLeftWidth: 4,
    borderLeftColor: colors.primary,
    backgroundColor: colors.surface,
    borderRadius: 8,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 12,
  },
  peCatalogTitle: {
    fontSize: Math.round(fontSize * 0.75),
    fontFamily: headingFont.fontFamily,
    fontWeight: headingFont.fontWeight,
    color: colors.textPrimary,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  });
};
