import { StyleSheet } from "react-native";
import { FontFamilyId, resolveAppFont, resolveBodyFont, resolveHeadingFont } from "../fontFamily";
import {
  BODY_LINE_HEIGHT,
  RUBRIC_LINE_HEIGHT,
  TITLE_LINE_HEIGHT,
  liturgyLineHeight,
} from "../liturgyTypography";

export const makeStyles = (
  colors: any,
  fontSize: number,
  fontFamilyId: FontFamilyId,
  isBold?: boolean,
  lineSpacing = 1,
) => {
  const bodyFont = resolveBodyFont(fontFamilyId, !!isBold);
  const headingFont = resolveHeadingFont(fontFamilyId);
  const subtitleFont = resolveAppFont(fontFamilyId, "bold");
  const lh = (pt: number, ratio: number) => liturgyLineHeight(pt, ratio, lineSpacing);
  const bodyLh = () => lh(fontSize, BODY_LINE_HEIGHT);
  const titlePt = (scale: number) => Math.round(fontSize * scale);

  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    topBar: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 8,
      minHeight: 56,
      minWidth: 56,
    },
    topBarLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginRight: 22,
      flexShrink: 0,
    },
    indiceBtn: {
      paddingHorizontal: 10,
      paddingVertical: 8,
      minHeight: 48,
      justifyContent: "center",
      borderWidth: 2,
      borderColor: colors.primary,
      borderRadius: 10,
      backgroundColor: colors.surface,
    },
    indiceBtnText: {
      fontSize: Math.round(fontSize * 0.55),
      color: colors.primary,
      fontWeight: "800",
    },
    backBtnText: {
      fontSize: Math.round(fontSize * 0.55),
      color: colors.textPrimary,
      fontWeight: "600",
    },
    title: {
      fontSize: Math.round(fontSize * 0.9),
      fontWeight: "700",
      color: colors.textPrimary,
      textAlign: "left",
    },
    pageIndicator: {
      minWidth: 108,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      paddingRight: 8,
    },
    pageIndicatorText: {
      fontSize: Math.round(fontSize * 0.55),
      color: colors.textSecondary,
      fontWeight: "600",
    },
    fontBtns: {
      flexDirection: "row",
      gap: 6,
      marginRight: 6,
      marginLeft: 6,
      alignItems: "center",
    },
    settingsBtn: {
      minWidth: 44,
      paddingHorizontal: 8,
      paddingVertical: 10,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
    },
    pageArea: {
      flex: 1,
      overflow: "hidden",
    },
    enginePaginatingOverlay: {
      ...StyleSheet.absoluteFillObject,
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
      backgroundColor: colors.background,
      opacity: 0.92,
      zIndex: 20,
      elevation: 20,
    },
    enginePaginatingText: {
      fontSize: Math.round(fontSize * 0.55),
      color: colors.textSecondary,
      fontWeight: "600",
    },
    // Stili nativi per i segmenti liturgici (PagerView + LiturgyPagedReader).
    nativeScroll: {
      flex: 1,
      backgroundColor: colors.background,
    },
    nativeContent: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 60,
    },
    // Viewport di lettura a tutta altezza.
    nativePage: {
      flex: 1,
      backgroundColor: colors.background,
    },
    nativePageContent: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    segSectionTitle: {
      fontSize: Math.round(fontSize * 1.05),
      fontFamily: headingFont.fontFamily,
      fontWeight: headingFont.fontWeight,
      color: colors.accentSection,
      marginTop: 16,
      marginBottom: 4,
      lineHeight: lh(titlePt(1.05), TITLE_LINE_HEIGHT),
    },
    segAntifonaTitle: {
      fontSize: titlePt(0.85),
      fontFamily: headingFont.fontFamily,
      fontWeight: headingFont.fontWeight,
      color: colors.accentAntifona,
      marginTop: 24,
      marginBottom: 4,
      lineHeight: lh(titlePt(0.85), TITLE_LINE_HEIGHT),
    },
    segReadingTitle: {
      fontSize: titlePt(0.85),
      fontFamily: headingFont.fontFamily,
      fontWeight: headingFont.fontWeight,
      color: colors.accentReading,
      marginTop: 14,
      marginBottom: 4,
      lineHeight: lh(titlePt(0.85), TITLE_LINE_HEIGHT),
    },
    segOrazioneTitle: {
      fontSize: titlePt(0.85),
      fontFamily: headingFont.fontFamily,
      fontWeight: headingFont.fontWeight,
      color: colors.accentOrazione,
      marginTop: 14,
      marginBottom: 4,
      lineHeight: lh(titlePt(0.85), TITLE_LINE_HEIGHT),
    },
    segSubtitle: {
      fontSize: titlePt(0.85),
      fontFamily: subtitleFont.fontFamily,
      fontWeight: subtitleFont.fontWeight,
      color: colors.textPrimary,
      marginTop: 12,
      marginBottom: 4,
      lineHeight: lh(titlePt(0.85), TITLE_LINE_HEIGHT),
    },
    // Titolo dei tropari della Formula C dell'Atto Penitenziale.
    segTroparioTitle: {
      fontSize: titlePt(0.85),
      fontFamily: headingFont.fontFamily,
      fontWeight: headingFont.fontWeight,
      color: colors.accentTropario,
      marginTop: 14,
      marginBottom: 4,
      lineHeight: lh(titlePt(0.85), TITLE_LINE_HEIGHT),
    },
    segPeTitle: {
      fontSize: titlePt(0.78),
      fontFamily: headingFont.fontFamily,
      fontWeight: headingFont.fontWeight,
      color: colors.accentPe,
      marginTop: 12,
      marginBottom: 6,
      lineHeight: lh(titlePt(0.78), TITLE_LINE_HEIGHT),
    },
    segNormal: {
      fontSize: fontSize,
      color: colors.textPrimary,
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      lineHeight: bodyLh(),
      marginTop: 4,
      marginBottom: 8,
    },
    segPeRubric: {
      fontSize: titlePt(0.85),
      color: colors.rubrics,
      fontStyle: "italic",
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      lineHeight: lh(titlePt(0.85), RUBRIC_LINE_HEIGHT),
      letterSpacing: 0.8,
      marginTop: 4,
      marginBottom: 8,
    },
    segRubric: {
      fontSize: titlePt(0.7),
      color: colors.rubrics,
      fontStyle: "italic",
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      lineHeight: lh(titlePt(0.7), RUBRIC_LINE_HEIGHT),
      marginVertical: 6,
    },
    segReadingRef: {
      fontSize: fontSize,
      color: colors.rubrics,
      fontStyle: "italic",
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      lineHeight: bodyLh(),
      marginTop: 4,
      marginBottom: 8,
    },
    segCelebrante: {
      fontSize: fontSize,
      color: colors.textPrimary,
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      lineHeight: bodyLh(),
      marginTop: 4,
      marginBottom: 8,
    },
    segAssemblea: {
      fontSize: titlePt(0.95),
      color: colors.textPrimary,
      fontStyle: "italic",
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      lineHeight: lh(titlePt(0.95), BODY_LINE_HEIGHT),
      marginTop: 4,
      marginBottom: 8,
    },
    segUmili: {
      fontSize: titlePt(0.85),
      color: colors.textPrimary,
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      lineHeight: lh(titlePt(0.85), BODY_LINE_HEIGHT),
      marginTop: 4,
      marginBottom: 8,
    },
    segSalmo: {
      fontSize: fontSize,
      color: colors.textPrimary,
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      lineHeight: bodyLh(),
      marginVertical: 6,
    },
    segPeConsecration: {
      fontSize: fontSize,
      lineHeight: bodyLh(),
      color: colors.accentPeConsecration,
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      marginTop: 4,
      marginBottom: 8,
    },
    segPeDossologia: {
      fontSize: fontSize,
      lineHeight: bodyLh(),
      color: colors.accentPeConsecration,
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      marginTop: 4,
      marginBottom: 8,
    },
    // R/. marker rosso bold (regola globale Preghiera dei Fedeli + salmo)
    segRespMarker: {
      color: colors.rubrics,
      fontFamily: headingFont.fontFamily,
      fontWeight: headingFont.fontWeight,
    },
    segSpacer: {
      height: 16,
    },
    // Spacer grande prima di una sezione con page-break (Liturgia della
    // Parola, post-Vangelo, Prefazio): non è una vera "pagina" ma una
    // separazione visiva ben evidente.
    segPageBreak: {
      height: 32,
      borderTopWidth: 2,
      borderTopColor: colors.border,
      marginTop: 32,
    },
    // Barra di progresso fissa in fondo alla pageArea. Sollevata di 10px dal
    // bordo per non essere coperta dai tasti di sistema su Android.
    progressTrack: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 10,
      height: 3,
      backgroundColor: colors.border,
    },
    progressFill: {
      height: 3,
      backgroundColor: colors.primary,
    },
    // ----- Tipografia (stessi colori/taglie di /messa) -----
    // I titoli sezione e PE hanno marginTop per respiro visivo quando seguono
    // testo precedente (l'orphan protection garantisce che il titolo non
    // resti mai solo in fondo a una pagina).
    sectionTitle: {
      fontSize: Math.round(fontSize * 1.05),
      fontFamily: headingFont.fontFamily,
      fontWeight: headingFont.fontWeight,
      color: colors.accentSection,
      marginTop: 14,
      marginBottom: 8,
      lineHeight: Math.round(fontSize * 1.15),
    },
    antifonaTitle: {
      fontSize: Math.round(fontSize * 0.85),
      fontFamily: headingFont.fontFamily,
      fontWeight: headingFont.fontWeight,
      color: colors.accentAntifona,
      marginTop: 10,
      marginBottom: 6,
      lineHeight: Math.round(fontSize * 0.95),
    },
    readingTitle: {
      fontSize: Math.round(fontSize * 0.85),
      fontFamily: headingFont.fontFamily,
      fontWeight: headingFont.fontWeight,
      color: colors.accentReading,
      marginTop: 10,
      marginBottom: 6,
      lineHeight: Math.round(fontSize * 0.95),
    },
    orazioneTitle: {
      fontSize: Math.round(fontSize * 0.85),
      fontFamily: headingFont.fontFamily,
      fontWeight: headingFont.fontWeight,
      color: colors.accentOrazione,
      marginTop: 10,
      marginBottom: 6,
      lineHeight: Math.round(fontSize * 0.95),
    },
    subtitle: {
      fontSize: Math.round(fontSize * 0.85),
      fontFamily: subtitleFont.fontFamily,
      fontWeight: subtitleFont.fontWeight,
      color: colors.textPrimary,
      marginTop: 8,
      marginBottom: 6,
      lineHeight: Math.round(fontSize * 0.95),
    },
    peTitle: {
      fontSize: Math.round(fontSize * 0.78),
      fontFamily: headingFont.fontFamily,
      fontWeight: headingFont.fontWeight,
      color: colors.accentPe,
      marginTop: 6,
      marginBottom: 10,
      lineHeight: Math.round(fontSize * 0.95),
    },
    peConsecration: {
      color: colors.accentPeConsecration,
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
    },
    peDossologia: {
      fontSize: fontSize,
      lineHeight: fontSize * 1.7,
      color: colors.textPrimary,
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      marginTop: 4,
      marginBottom: 8,
    },
    umili: {
      fontSize: Math.round(fontSize * 0.85),
      fontStyle: "italic",
      color: colors.rubrics,
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      marginVertical: 6,
      lineHeight: fontSize * 1.55,
    },
    text: {
      fontSize: fontSize,
      lineHeight: fontSize * 1.7,
      color: colors.textPrimary,
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      marginTop: 0,
      marginBottom: 8,
    },
    rubric: {
      fontSize: Math.round(fontSize * 0.7),
      fontStyle: "italic",
      color: colors.rubrics,
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      marginVertical: 4,
      lineHeight: fontSize * 1.2,
    },
    salmoRit: {
      color: colors.rubrics,
      fontFamily: headingFont.fontFamily,
      fontWeight: headingFont.fontWeight,
    },
    salmoText: {
      fontSize: fontSize,
      lineHeight: fontSize * 1.55,
      color: colors.textPrimary,
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      marginVertical: 4,
    },
    celebrante: {
      fontSize: fontSize,
      color: colors.textPrimary,
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      marginVertical: 6,
      lineHeight: fontSize * 1.7,
    },
    assemblea: {
      fontSize: Math.max(12, fontSize - 1),
      fontStyle: "italic",
      color: colors.textPrimary,
      fontFamily: bodyFont.fontFamily,
      fontWeight: bodyFont.fontWeight,
      marginVertical: 6,
      lineHeight: fontSize * 1.7,
    },
    // ----- Empty state -----
    emptyBox: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      padding: 32,
      gap: 20,
    },
    emptyTitle: {
      fontSize: Math.round(fontSize * 0.9),
      fontWeight: "800",
      color: colors.textPrimary,
      textAlign: "center",
    },
    emptyText: {
      fontSize: Math.round(fontSize * 0.65),
      color: colors.textSecondary,
      textAlign: "center",
      lineHeight: fontSize * 1.3,
    },
    modalList: {
      padding: 20,
      gap: 12,
    },
    listItem: {
      padding: 18,
      borderWidth: 2,
      borderColor: colors.border,
      borderRadius: 12,
      backgroundColor: colors.surface,
      minHeight: 64,
    },
    listItemActive: {
      borderColor: colors.primary,
      borderWidth: 4,
    },
    listItemText: {
      fontSize: Math.round(fontSize * 0.8),
      color: colors.textPrimary,
      fontWeight: "700",
    },
    listItemSub: {
      fontSize: Math.round(fontSize * 0.55),
      color: colors.textSecondary,
      marginTop: 4,
    },
    primaryBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: 24,
      paddingVertical: 16,
      borderRadius: 14,
      backgroundColor: colors.primary,
      minHeight: 64,
    },
    primaryBtnText: {
      fontSize: Math.round(fontSize * 0.75),
      fontWeight: "700",
      color: colors.onPrimary,
    },
  });
};
